### ISSUE TITLE
Menu Question

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#1]
Both of these menu's have the same items listed. Is this supposed to be that way? Or is one of the menu's supposed to have the About Us, Contact Us, etc. pages?

![screen shot 2017-12-11 at 9 31 39 am](https://user-images.githubusercontent.com/11448089/33844803-4eedf370-de56-11e7-9bb4-3837e34f096d.png)

**Comment by influxweb** [comment]
In the case of you being on a category page, this is entirely possible. The top menu is the navigation bar and the second one is the category tree. Depending on the navigation set up and if you are on a parent category or a child, your category tree will change.
