### ISSUE TITLE
Formatting issue - Firefox Ipad

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#11]
Where it has "Other State / Province" are the boxes supposed to be jumbled like this or aligned?

![screen shot 2018-02-12 at 11 05 57 am](https://user-images.githubusercontent.com/11448089/36114417-da8be27e-0fe4-11e8-84f0-423153bb534b.png)

**Comment by influxweb** [comment]
Looks like the iPad Pro is a weird one. The code has been update and will be in the next package.
