### ISSUE TITLE
Stored Credit Card still asking for CC Number

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#12]
Explorer:

When I go to checkout I choose a stored credit card:

![screen shot 2018-02-12 at 11 15 15 am](https://user-images.githubusercontent.com/11448089/36114866-20b3342c-0fe6-11e8-9387-3a304a6f6420.png)

But when I get to the next page, it's asking me to put the credit card number in again. If a card is store, shouldn't the number appear in this box?

![screen shot 2018-02-12 at 11 15 24 am](https://user-images.githubusercontent.com/11448089/36114894-3a0a3880-0fe6-11e8-9ad8-4f4954332b20.png)

**Comment by influxweb** [comment]
I believe, for security purposes, the actual card number is not displayed. In it's place, the "Card ending in XXXX" is there.
