### ISSUE TITLE
Spacing issue on Mobile

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#13]
On both Chrome and Explorer, when you are in mobile state and click on the drop down menu, then click on the 2nd drop down menu, there needs to be some padding added before navigation links. 

![screen shot 2018-02-12 at 11 36 15 am](https://user-images.githubusercontent.com/11448089/36115836-25df53ba-0fe9-11e8-8071-19a83f7ae1f7.png)
![screen shot 2018-02-12 at 11 36 42 am](https://user-images.githubusercontent.com/11448089/36115837-25ff3068-0fe9-11e8-8afa-71ecfd66912b.png)

**Comment by influxweb** [comment]
This is a non-issue as this functionality is still in the development stage and not ready for quality assurance.
