### ISSUE TITLE
Mobile Menu Doesn't Work on secondary pages.

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#14]
When clicking on the mobile drop down... Let's say you click on "About Us" and it takes you to that page. There is then what looks like another drop down (with lines), but when you click on it nothing happens in mobile view. Do those lines signify that there is a drop down? 
![mobile-menu](https://user-images.githubusercontent.com/11448089/36116088-f85d6cc8-0fe9-11e8-95d8-767be129532c.png)

**Comment by mivajenn** [comment]
It also doesn't work on mobile in this area.

![screen shot 2018-02-12 at 11 44 49 am](https://user-images.githubusercontent.com/11448089/36116144-2ccf767c-0fea-11e8-87fa-66aa6dd37b86.png)

**Comment by influxweb** [comment]
This is a non-issue as this functionality is still in the development stage and not ready for quality assurance.
