### ISSUE TITLE
? When you Sign in to your account, this is the page it takes you to?

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#15]
When you sign in to your account from the top right sign up button, it takes you to the sign in page -
 which is very confusing. Wouldn't it be better to take you to your account page vs the sign in page.

![screen shot 2018-02-12 at 11 56 49 am](https://user-images.githubusercontent.com/11448089/36116692-fe4b29ac-0feb-11e8-865a-f99cbe351e7c.png)

**Comment by mivajenn** [comment]
It would make more sense to bring you to this page:
![screen shot 2018-02-12 at 11 58 28 am](https://user-images.githubusercontent.com/11448089/36116715-15c92fc0-0fec-11e8-9c03-00ead336fed1.png)

**Comment by influxweb** [comment]
What page were you on when you signed in?

**Comment by mivajenn** [comment]
ah, wasn’t sure so I just tried signing in from four different pages and it brought me right back to the page I was last on. So I guess that’s what it does.

Jenn Rawlings
Assistant to the VP of Developer Relations / Miva, Inc.
www.miva.com<http://www.miva.com/>

Twitter<http://www.miva.com/social/twitter> | Facebook<http://www.miva.com/social/facebook> | Instagram<http://www.miva.com/social/instagram> | LinkedIn<http://www.miva.com/social/linkedin> | Blog<http://www.miva.com/blog>

[http://www.miva.com/images/new-images/miva-email-sig.gif]<http://www.miva.com/>

On Feb 12, 2018, at 12:00 PM, Matt Zimmermann <notifications@github.com<mailto:notifications@github.com>> wrote:


What page were you on when you signed in?

**Comment by influxweb** [comment]
Yeah, that's the functionality of the new log in process.
