### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#16]
If I try and login with just my email and click Log In, it doesn't give me an error message telling me to enter my password. It doesn't give any error message. (other than the one saying my site isn't secure). Should it?

![screen shot 2018-02-12 at 12 00 01 pm](https://user-images.githubusercontent.com/11448089/36116809-68ad8de4-0fec-11e8-80c5-eb2ec032df60.png)

**Comment by mivajenn** [comment]
I just left the password blank, which is on my checklist to do. So not wrong information, just lack of information.

Jenn Rawlings
Assistant to the VP of Developer Relations / Miva, Inc.
www.miva.com<http://www.miva.com/>

Twitter<http://www.miva.com/social/twitter> | Facebook<http://www.miva.com/social/facebook> | Instagram<http://www.miva.com/social/instagram> | LinkedIn<http://www.miva.com/social/linkedin> | Blog<http://www.miva.com/blog>

[http://www.miva.com/images/new-images/miva-email-sig.gif]<http://www.miva.com/>

On Feb 12, 2018, at 12:05 PM, Matt Zimmermann <notifications@github.com<mailto:notifications@github.com>> wrote:


You shouldn't be able to proceed without have both the required fields filled in. If you have incorrect information, do you get the error message?

**Comment by mivajenn** [comment]
So it does this from both the regular sign in page as well as the account sign in on the top right. If I put in my login info, but leave the password blank, it doesn't give me an error message, it just sits there after I hit Sign In

**Comment by mivajenn** [comment]
![screen shot 2018-02-12 at 12 07 43 pm](https://user-images.githubusercontent.com/11448089/36117159-7eb4c11a-0fed-11e8-9b97-09a4921614c3.png)

**Comment by influxweb** [comment]
Hmm, from the top log in form, that should not be possible. If you do not have a password, it should take you to the log in page with the Miva error being displayed.
