### ISSUE TITLE
Text still off centered on Prods

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#17]
I thought this was part of the last changes, but the text is still off under the products. This is in Safari.

![screen shot 2018-02-12 at 1 10 02 pm](https://user-images.githubusercontent.com/11448089/36119874-37b0c2c4-0ff6-11e8-8540-565ff6474c25.png)

**Comment by influxweb** [comment]
This will be fixed in the 9.8 release - see #5
