### ISSUE TITLE
Why does Paypal Appear here?

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#19]
I'm checking out and using a Visa, but there's a big PayPal button above my credit card fields. I remember this from the past, but can't remember why it's there. 

As part of my testing I turned off MivaPay and then this showed up.

Thanks
![screen shot 2018-02-12 at 1 22 34 pm](https://user-images.githubusercontent.com/11448089/36120408-eeb883a2-0ff7-11e8-95da-6cc11259f81f.png)

**Comment by influxweb** [comment]
What payment gateway are you using by default? If it's PayPal or BrainTree, then the button might appear.

**Comment by mivajenn** [comment]
Not sure, I turned off MivaPay as part of my testing … so whatever the store is defaulting to.

Jenn Rawlings
Assistant to the VP of Developer Relations / Miva, Inc.
www.miva.com<http://www.miva.com/>

Twitter<http://www.miva.com/social/twitter> | Facebook<http://www.miva.com/social/facebook> | Instagram<http://www.miva.com/social/instagram> | LinkedIn<http://www.miva.com/social/linkedin> | Blog<http://www.miva.com/blog>

[http://www.miva.com/images/new-images/miva-email-sig.gif]<http://www.miva.com/>

On Feb 12, 2018, at 1:29 PM, Matt Zimmermann <notifications@github.com<mailto:notifications@github.com>> wrote:


What payment gateway are you using by default? If it's PayPal or BrainTree, then the button might appear.

**Comment by influxweb** [comment]
There's nothing installed by default, so one of those two was probably activated for use.
