### ISSUE TITLE
Mini Cart Question

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#2]
When you add an item to the cart, it brings up the mini cart and your options are to edit the cart or to checkout. Shouldn't there be a "continue shopping?" option? 

![screen shot 2017-12-11 at 10 30 48 am](https://user-images.githubusercontent.com/11448089/33847153-7a26cf96-de5e-11e7-9722-e815b3559feb.png)

**Comment by influxweb** [comment]
I'll add in a continue option as a link below the buttons.

**Comment by influxweb** [comment]
A continue shopping link has been added below the CTA section.
