### ISSUE TITLE
Partial Credit isn't working

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#3]
I have $50 credit on my account, when I choose to apply credit to my cart, then choose partial payment, I chose $10, when I submitted that, it doesn't apply it. So something is wrong with this feature.

![screen shot 2017-12-11 at 10 34 48 am](https://user-images.githubusercontent.com/11448089/33847365-1984dc72-de5f-11e7-8411-f0225647959b.png)
![screen shot 2017-12-11 at 10 35 05 am](https://user-images.githubusercontent.com/11448089/33847366-199da2fc-de5f-11e7-8e6c-90ccc2a6dc4d.png)

**Comment by mivajenn** [comment]
If you choose to use the full amount, it works. Just not partial.

**Comment by influxweb** [comment]
I'll check into this.

**Comment by influxweb** [comment]
I am unable to duplicate this issue. Are you not seeing the credit applied in the order summary or is it no accepting the partial at all?

**Comment by mivajenn** [comment]
it doesn’t accept partial at all.

Which store is this again and I’ll test again.

Jenn Rawlings
Graphic Designer / Miva, Inc.
www.miva.com<http://www.miva.com/>

Twitter<http://www.miva.com/social/twitter> | Facebook<http://www.miva.com/social/facebook> | Instagram<http://www.miva.com/social/instagram> | LinkedIn<http://www.miva.com/social/linkedin> | Blog<http://www.miva.com/blog>

[http://www.miva.com/images/new-images/miva-email-sig.gif]<http://www.miva.com/>

On Dec 20, 2017, at 9:09 AM, Matt Zimmermann <notifications@github.com<mailto:notifications@github.com>> wrote:


I am unable to duplicate this issue. Are you not seeing the credit applied in the order summary or is it no accepting the partial at all?

**Comment by influxweb** [comment]
This would be for the Shadows store. I'm not sure if you saw this issue on your own installation of it or on the demo site [ [http://shadows.mivareadythemes.com/](http://shadows.mivareadythemes.com/) ].
