### ISSUE TITLE
No Error Message

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#4]
I put my last name in the credit card spot and tried checking out - it wouldn't process or let me go to the next page but it also didn't give me an error code or highlight the card section so I would know where I messed up 

![screen shot 2017-12-11 at 10 50 32 am](https://user-images.githubusercontent.com/11448089/33847993-3e96de28-de61-11e7-95ff-3994127f398d.png)

**Comment by influxweb** [comment]
Which payment gateway are you using and do you have MivaPay enabled?

**Comment by influxweb** [comment]
That is actually the correct functionality. If the credit card field does not contain a valid number, you cannot continue. I have added some visual validation to the field so you know there is an error.
