### ISSUE TITLE
Minibasket Attribute Pricing Issues 

### ISSUE THREAD

**Issue by bdepauw** [mivaecommerce/readytheme-shadows#41]
## Expected Behavior
-  We’ll need to update minibasket to include attribute pricing information

## Current Behavior
-  The minibasket product information does not display or take into account attribute pricing.  So if I have $9 product, and $10 attribute, the minibasket shows that the item is $9. 
-  In the default state, the minibasket also does not show the product’s correct sale price when the item has attribute pricing.

## Attempted Fixes
-  FIX: Change the &mvt:item:formatted_subtotal; variable to instead use a custom calculated item subtotal to show the correct price, both taking into account attributes as well as discounts. The calculation should be the group:subtotal + looping through and adding in all option:subtotal values for that item’s attributes. 
-  I’ve attached a screenshot of my example code for the fix as well.  
-  For future reference: I was going to suggest we use the subtotal_comprehensive variables as a solution, but this led me to discover some issues with the subtotal_comprehensive variables available to us that Jon has now filed a bug for v10.  
![shadows_minibasket_missingattributeprices_fixcode](https://user-images.githubusercontent.com/17090739/46373333-9bdea100-c642-11e8-8d1c-20aa5fd50ef1.jpg)

## Steps to Reproduce (for bugs)
-  See Screenshot Attached
![shadows_minibasket_missingattributeprices](https://user-images.githubusercontent.com/17090739/46373335-9bdea100-c642-11e8-9536-bff7db22ec87.jpg)

*Chrome / Windows10 / Desktop

**Comment by influxweb** [comment]
This was addressed in Issue #39
