### ISSUE TITLE
PROD Pricing Display Issues 

### ISSUE THREAD

**Issue by bdepauw** [mivaecommerce/readytheme-shadows#42]
## Expected Behavior
-  Attribute pricing should display the discounted amount on the PROD page to reflect accurate product pricing. 

## Current Behavior
-	Shadows does not include the feature we had in the Levels theme that would (when a product does not have variants generated for it), on the selection of attributes, take the attribute pricing and add it to the product price, and then update the total price at the top, just like attribute machine does for items with variants.  This is a great and desired feature by our merchants, especially if they have a combination of some items with variants and some without on their store, to keep the user experience consistent.  
-	More importantly though, when a product (without variants) has attribute pricing and there is a discount being applied to the product the price on the PROD page does not reflect the true price of the item.  If I had a $10 product and $10 attribute getting 50% off, the product page will look like the cost of the product is $15 rather than $10.  This is big issue for our merchants since it may cause customers to decide to not add the item to their cart since they think it will be more expensive.  This has always been an issue in Miva, and awhile back I created some custom code to be inserted on the PROD page attribute template to do an attribute discount price fix.  I’d suggest we have someone do some extra testing with this solution to ensure there is nothing I’ve missed, and then consider adding it into future themes until software eventually updates the attribute & option prices to include sale pricing.

## Attempted Fixes
-    I’ve attached the sample code to this email and here is also the blog post I previously wrote on it:
-    http://blog.merchant.local/?p=3823 
-    https://gist.github.com/bdepauw/cada3c528611b6b171c64bc5bbc04640

![shadows_prod_pricingdisplayissues_fixscreen](https://user-images.githubusercontent.com/17090739/46373813-df85da80-c643-11e8-8709-b4be71413ddd.jpg)

## Steps to Reproduce (for bugs)
- See Screenshots
![shadows_prod_pricingdisplayissues](https://user-images.githubusercontent.com/17090739/46373812-df85da80-c643-11e8-97df-9f5c20ad710b.jpg)

Chrome / Windows10 / Desktop

**Comment by influxweb** [comment]
At this time, we have no plans on adding this functionality into the Shadows ReadyTheme. We may release an extension down the road on its own or tied to a different ReadyTheme, but this will be based on how requested this feature is and if it will be included natively in Miva v10.
