### ISSUE TITLE
PROD/WLGN/LOGN/WISH/CACT/BASK - Wishlist and New User Registration 

### ISSUE THREAD

**Issue by cam424** [mivaecommerce/readytheme-shadows#43]
When a user adds something to their wishlist but doesn't have an account, then proceeds to sign up for an account, the product does not get added to their Wishlist. Furthermore, users end up on their WISH page and clients may lose conversions because it doesn't even navigate back to the previous product they wanted to add in the first place. Additionally, when a user without an account checks their basket and clicks "save for later" to move all items to their wishlist, the items are lost if they go through the registration process.

## Expected Behavior
Users should be able to enter the registration process from the PROD page or BASK page via adding items to their Wishlist without items getting lost in the mix.

Consider using session IDs or basket IDs to save this information while the user completes their registration process and then create a wishlist and add item(s) to the new wishlist.

## Current Behavior
Described in summary

## Attempted Fixes
As a quick fix, I hid the save for later feature on BASK for users that aren't logged in. For the PROD/WLGN/LOGN/CACT/WISH process, I've passed the product ID and other basic info like quantity, category, etc throughout the process and added steps to create a default wishlist after user registration is complete on CACT. The meta refresh then takes the user back to the product they were looking at. When I tried to send the item to the newly created wishlist, I encountered a 403 forbidden. I began to set up passing along attributes but felt that with the 403 and knowing that we use sessions in other aspects of the site, there may be a better way to accomplish this.

## Steps to Reproduce (for bugs)
Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant

### A. PROD to wishlist
1. Be a guest user without an account.
2. Navigate to PROD.
3. Add product to wishlist.
4. Select Register on WLGN.
5. Proceed to register as a new user on LOGN.
6. Wait for info to continue through to CACT and the redirect to WISH.
7. Notice product does not get added to wishlist.

### B. BASK save for later
1. Be a guest user without an account.
2. Add several items to cart.
3. Navigate to BASK
4. Save items for later.
5. Repeat registration process mentioned in A.
6. Notice items are lost.

## Context
A client has launched their new Shadows site and is experiencing issues with their users claiming their site is broken. We've improved the experience a bit with hiding features behind a check for logged in users and adjusting redirects, but it still isn't ideal for overall UX.

## Your Environment
All platforms.
All browsers.

**Comment by influxweb** [comment]
Thank you for your insights on this. Sadly, the functionality you are talking about is platform inherent. I will add this to the enhancement list for a future release and see what I can do to make the process as smooth as possible for customers without an existing account.
