### ISSUE TITLE
Tablet Breakpoints causing Navigation Double Click Issue

### ISSUE THREAD

**Issue by cam424** [mivaecommerce/readytheme-shadows#44]
On the Shadows demo and live client sites using the same theme, when viewing a site on a tablet with a breakpoint over 960px, the site is displaying as it would on desktop. For navigation items, this means that anything below top level list items requires a double click in order to visit the page, with the first click triggering a hover effect if present. 

## Expected Behavior
Transfigured Navigation should be present for a higher range of resolutions when using tablet to avoid the double clicking requirement when using the navigation links.

## Current Behavior
Navigation present on larger tablets (ipad pro for example), is showing the default desktop display. This requires users to double click navigation items below the top level. 

My recommendnation would be to increase the 960 breakpoint to ~1366 and create additionally  specific min-device-width, orientation, -webkit-min-device-pixel-ratio queries for tablet users like the transfiguration trigger point to ensure a consistent experience for actual desktop users, while creating a true tablet experience for people using tablet devices, we could come up with a better crossover resolution experience for large tablet users despite their resolution range falling within the standard range for smaller desktop users.

## Attempted Fixes
None yet.

## Steps to Reproduce (for bugs)
Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant

1. Navigate to https://shadows.mivareadythemes.com on an ipad pro or similarly sized mobile device with a breakpoint over 960
2. Hover over any top level navigation item that has children
3. Click on one of the child links
4. Click again.
5. Notice that it requires two clicks to actually visit link.

## Context
Our client has noticed a drop in their tablet user conversions and is worried about how this is affecting their bottom line. 

## Your Environment

Mobile Devices with a break point >960px; ie: IPad Pro

**Comment by influxweb** [comment]
The size of the touch device has no bearing on this functionality. To accommodate for a `hover` function when using touch, we utilize a version of [DoubleTapToGo](https://osvaldas.info/drop-down-navigation-responsive-and-touch-friendly) which allows a user to trigger a parent element, so its children are visible, without navigating to the parent link.
