### ISSUE TITLE
Product Name and Price seem off centered

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#5]
Not sure if it's meant to be that way, but the product name and price aren't right justified or centered, it's just kinda "off" ... see attachment. 

[
<img width="1440" alt="screen shot 2017-12-27 at 11 37 33 am" src="https://user-images.githubusercontent.com/11448089/34391428-5d147342-eafa-11e7-97d4-dff116796a8e.png">
](url)

**Comment by influxweb** [comment]
My guess is the images are not the proper size. The default size is usually 234 pixels. Change that to 360 and everything should line up.

**Comment by mivajenn** [comment]
I thought sample products or default product image size is 800x800?

Jenn Rawlings
Assistant. to VP Developer Relations / Miva, Inc. / Miva, Inc.

www.miva.com<http://www.miva.com/>

Twitter<http://www.miva.com/social/twitter> | Facebook<http://www.miva.com/social/facebook> | Instagram<http://www.miva.com/social/instagram> | LinkedIn<http://www.miva.com/social/linkedin> | Blog<http://www.miva.com/blog>

[http://www.miva.com/images/new-images/miva-email-sig.gif]<http://www.miva.com/>

On Dec 27, 2017, at 11:41 AM, Matt Zimmermann <notifications@github.com<mailto:notifications@github.com>> wrote:


My guess is the images are not the proper size. The default size is usually 234 pixels. Change that to 360 and everything should line up.

**Comment by influxweb** [comment]
You can set the display size for these images in the ReadyTheme component. When it is first initialized, it is set to 234x234 which is too small.

**Comment by mivajenn** [comment]
![screen shot 2018-01-26 at 11 45 45 am 2](https://user-images.githubusercontent.com/11448089/35457657-8b7eeb80-028e-11e8-979a-fbe03d3f2202.png)

**Comment by influxweb** [comment]
This has been confirmed as a bug in the software; it only happens when in Advanced Mode.  It should be fixed in the 9.08.00 software release.
