### ISSUE TITLE
Continue Shopping should be added to the mini cart

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#7]
![screen shot 2018-02-02 at 3 08 25 pm](https://user-images.githubusercontent.com/11448089/35758876-08814c76-082b-11e8-8e32-2bab43fe1b87.png)

**Comment by influxweb** [comment]
There is one on the demo store. Are you using the latest build?

⁣Sent from TypeApp ​

**Comment by mivajenn** [comment]
Well, I’m at home and used the one that says “here’s the file that includes the fonts in them.”

Is that the correct one?

Jenn Rawlings
Assistant to the VP of Developer Relations / Miva, Inc.
www.miva.com<http://www.miva.com/>

Twitter<http://www.miva.com/social/twitter> | Facebook<http://www.miva.com/social/facebook> | Instagram<http://www.miva.com/social/instagram> | LinkedIn<http://www.miva.com/social/linkedin> | Blog<http://www.miva.com/blog>

[http://www.miva.com/images/new-images/miva-email-sig.gif]<http://www.miva.com/>

On Feb 2, 2018, at 3:34 PM, Matt Zimmermann <notifications@github.com<mailto:notifications@github.com>> wrote:

There is one on the demo store. Are you using the latest build?

⁣Sent from TypeApp ​
