### ISSUE TITLE
Category Header is showing up on the Product pages

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#8]
![screen shot 2018-02-02 at 3 10 20 pm](https://user-images.githubusercontent.com/11448089/35758912-345ee89e-082b-11e8-8c71-c2e58e594785.png)

**Comment by influxweb** [comment]
This issue has been corrected.
Update your product page header and footer tags with the following:
```
<mvt:item name="prod_ctgy_hdft" param="prod_header" />
```
```
<mvt:item name="prod_ctgy_hdft" param="prod_footer" />
```
