### ISSUE TITLE
Quantify issue on BASK - item gets remove on "enter" key

### ISSUE THREAD

**Issue by gdcolin** [mivaecommerce/readytheme-shadows#80]
Provide a general summary of the issue in the Title above

## Expected Behavior
Nothing, or something that makes sense: anything but removal

## Current Behavior
Apparently this works fine in Chrome and Edge, not in Firefox:

    1.add an item to your cart
    2.go to basket
    3.update quantity (to more then what you have)
    4.click enter instead of the plus button
    ===
	result is the item is removed from cart completely

## Attempted Fixes
I usually just pull out all automation and add update / remove buttons but I'm tired of doing that. Can this be fixed for real?

## Context
Tired of pulling functionalty and want it fixed for real.

**Comment by influxweb** [comment]
I believe this issue was addressed in v1.0.5 #59 What version is your site running and are you able to duplicate the issue on the [demonstration site](https://shadows.mivareadythemes.com/)?

**Comment by gdcolin** [comment]
We had to wait until after crazy season weekend to put in the fix but the version of quantify.js here https://shadows.mivareadythemes.com/mm5/themes/shadows/extensions/quantify/quantify.js did not have the issue. Thank you for letting us know and you can mark this as "some idiot opened a task about something already fixed" / closed.
