### ISSUE TITLE
Sign Up Form In Chrome Attaching To Login

### ISSUE THREAD

**Issue by ChildeRoland840** [mivaecommerce/readytheme-shadows#87]
In Chrome, latest build and previous I've noticed for a while now the "quick" register form on LOGN is failing when trying to register a new account The "register" form seems to submit the "sign in" form instead of the register form.  Doesn't present in Edge (didn't try Firefox or Safari).  I've noticed this across numerous installs with a variety of Shadows versions.  Email me for links if needed.

**Comment by influxweb** [comment]
What version of Shadows are you seeing this on? I have tested the process and are unable to duplicate it. If you can post a link, I can take a look. Additionally, can you try and duplicate it on the demonstration site: [https://shadows.mivareadythemes.com/customer-login.html](https://shadows.mivareadythemes.com/customer-login.html)

**Comment by ChildeRoland840** [comment]
Hmmmmm, I tried your link, first try, it did the bad thing and through the
error up.  Since then, it's been working as I tried to replicate it
a second and third time.  I tried a boatload of times actually to try and
replicate the issue with no luck.  I don't want to share a link publicly
here as these are clients dev sites.  If you could email me separate from
this I can provide it.  I also have a video demonstrating it as well on
that dev install.
