### ISSUE TITLE
Why are action buttons not bolder

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-shadows#9]
When signing up for an account, or in the two instances below - why aren't the call to action buttons black or bolder?

In first example, the Create My Account button should be bolder, not the login.

![screen shot 2018-02-12 at 9 54 45 am](https://user-images.githubusercontent.com/11448089/36111789-2cee5460-0fdc-11e8-84eb-7bc444443e8e.png)

In the second example, the save button should be bolder.
![screen shot 2018-02-12 at 10 03 41 am](https://user-images.githubusercontent.com/11448089/36111790-2d0aefa8-0fdc-11e8-946d-c6aea4c0533a.png)

**Comment by influxweb** [comment]
It is a designer prerogative which can be altered by the developer if they would like to.
